### ISSUE TITLE
Custom image URL/Domain model

### ISSUE THREAD

**Issue by jsthon** [flagrow/flarum-ext-image-upload#13]
Add the custom image URL/Domain model, It can be use for CDN. :)

**Comment by Luceos** [comment]
So instead of using only local storage, you want to be able to specify a CDN root URL in case you're using a CDN? Any requirements you can think of that would make this a top notch feature implementation? We don't like to do half work ;)

**Comment by Luceos** [comment]
What is the reason for closing this issue @jsthon , I actually like the request.

**Comment by jsthon** [comment]
I'm sorry... :(
My English is poor. I try my best to describe, hope you could understand it.

The function can custom the root URL of the images.
> Example URL: **//example.com/**assets/images/example.jpg

Among the "**//example.com/**" is "**root URL**".


If we need to loading these images(local storage) by **CDN** , so the "**root URL**" need change to "**//CDN.example.com/**".

**Comment by Luceos** [comment]
This will be released in 0.2.0 - this requires beta 5 though.

https://github.com/flagrow/flarum-ext-image-upload/pull/25

**Comment by jsthon** [comment]
Thanks! :+1:
