### ISSUE TITLE
Can't start discussion after enabling extension

### ISSUE THREAD

**Issue by tobscure** [flagrow/flarum-ext-image-upload#34]
After enabling the extension, the follow JavaScript error occurs when the "Start a Discussion" button is clicked:

```text
Uncaught TypeError: Cannot read property 'canUploadImages' of undefined
```

Referring to this line in main.js:

```
if (!discussion.canUploadImages()) return;
```

This is with 0.2.0.

**Comment by Luceos** [comment]
Priority issue.
