### ISSUE TITLE
How can I use https with Imgur

### ISSUE THREAD

**Issue by skywalker512** [flagrow/flarum-ext-image-upload#41]
How can I use https with Imgur
In China http is not can access
but https is OK
so how can I use https with Imgur

**Comment by Luceos** [comment]
Can't really find documentation that all uploaded images have https.. We could run a check after changing http to https, and it does make sense..

**Comment by skywalker512** [comment]
I just want to know how to use https with Imgur.Beacuse in China I can't use http which is intercepted.

**Comment by skywalker512** [comment]
l means what code can change the url with http to https @Luceos

**Comment by Luceos** [comment]
If you'd like to try and send in a Pull Request that would be great, the following line needs to replace http with https:

https://github.com/flagrow/flarum-ext-image-upload/blob/master/src/Adapters/ImgurAdapter.php#L57

**Comment by Luceos** [comment]
@skywalker512 have you been able to implement this? Otherwise I'd prefer having this one open in order to implement it ourselves.

**Comment by skywalker512** [comment]
I add the 

    $meta = preg_replace("/^http:/i", "https:", $meta);
    return $meta;
on the https://github.com/flagrow/flarum-ext-image-upload/blob/master/src/Adapters/ImgurAdapter.php#L58

**Comment by Luceos** [comment]
merged and version 0.2.2 tagged

**Comment by datitisev** [comment]
Shouldn't this be closed now?
