### ISSUE TITLE
size validation does not work

### ISSUE THREAD

**Issue by Luceos** [flagrow/flarum-ext-image-upload#44]
https://discuss.flarum.org/d/1836-flagrow-image-uploader-for-flarum-forum-messages/126

**Comment by santiagobiali** [comment]
Fixed https://github.com/flagrow/flarum-ext-image-upload/commit/1ceb89cf25b60b76187bb9fa5ecf80d3331a92f3

**Comment by Luceos** [comment]
Nice solution, would never have thought to solve it with a public property! :+1:
