### ISSUE TITLE
Broken translation?

### ISSUE THREAD

**Issue by sempixel** [flagrow/flarum-ext-image-upload#51]
I've installed this extension on a fresh new beta 5 but I can't get translation displayed.

![capture d ecran 2016-09-28 a 09 58 09](https://cloud.githubusercontent.com/assets/1658628/18905149/1d102312-8562-11e6-9c50-56197d9da91a.png)

I've deleted storage cache and removed assets `.js`

What can I do more?

Thanks.

**Comment by Luceos** [comment]
Try re-enabling a random extension in your admin cp.

**Comment by sempixel** [comment]
Well. I enabled Akismet. Nothing.
Disabled. Nothing.
Switched back to EN. Still Nothing.

**Comment by Luceos** [comment]
What version of the extension do you have installed and what language do you have selected?

**Comment by sempixel** [comment]
`0.2.3` and I tried it with EN and FR.

**Comment by Luceos** [comment]
Did you delete all `assets/*.js`?

**Comment by sempixel** [comment]
Sure. Just did again right now.
Translation still not displaying.

**Comment by Luceos** [comment]
CloudFlare enabled by any chance?

**Comment by sempixel** [comment]
@Luceos it was almost that. There is a Varnish cache activated on my hosting.

2 hours passed, I was afk and it now works. How cool is that!

Thanks for your time!

**Comment by Luceos** [comment]
No problem. Glad it got solved.
