### ISSUE TITLE
flarum dev-master 版本的后台设置无法使用

### ISSUE THREAD

**Issue by Btitle** [flagrow/flarum-ext-image-upload#52]
flarum dev-master 版本的后台设置无法使用，请求有空能更新一下适配dev-master版本的。

**Comment by Luceos** [comment]
Please write an issue understandable in English and I give an answer. Closing until then.

**Comment by Btitle** [comment]
Hi @luceos Flarum-ext-image-upload could not be used in the dev-master flarum version.

**Comment by Luceos** [comment]
dev-master is not production ready, so it only makes sense that a stable version of an extension doesn't work with an unreleased version of Flarum.

**Comment by Btitle** [comment]
ok,thinks
