### ISSUE TITLE
Settings not defined in admin panel?

### ISSUE THREAD

**Issue by dav-is** [flagrow/flarum-ext-image-upload#54]
When opening the admin panel in beta 6, it throws this error:
`
admin:89 Uncaught TypeError: Cannot read property 'flagrow.image-upload.availableUploadMethods' of undefined
`

The  settings model won't open either.

**Comment by Luceos** [comment]
Thanks for reporting, from what I've seen all Flagrow extensions might need an update. As communicated on the Flarum official discussion board I'll pick this up the coming weeks.

**Comment by Luceos** [comment]
@dav-is the extension is fixed now.
